name: MarkdownConverter
kind: pipeline
type: docker

steps:
- name: install
  image: node
  commands:
  - npm install
- name: lint
  image: node
  commands:
  - npm run lint
- name: build
  image: node
  commands:
  - npm run build
- name: test
  image: manuth/vscode-test-runner
  commands:
  - xvfb-run npm run test

trigger:
  branch:
  - master
  - dev