name: MarkdownConverter
kind: pipeline
type: docker

steps:
- name: install
  image: node
  commands:
  - npm install
- name: lint
  image: node
  commands:
  - npm run lint
- name: build
  image: node
  commands:
  - npm run build
- name: test
  image: manuth/vscode-test-runner
  commands:
  - xvfb-run npm run test
- name: build extension
  image: node
  commands:
  - npx vsce package
  when:
    event:
    - tag
- name: release notes
  image: ubuntu
  commands:
  - cp -f CHANGELOG.md ReleaseNotes.md
  - sed -i '0,/## .* v[0-9.]*/{ /## .* v[0-9.]*/P ; d } ; /## .* v[0-9.]*/,$d' ReleaseNotes.md
  - cp -f ReleaseNotes.md ReleaseTitle.md
  - sed -i '2,$d ; s/## \(.* v[0-9.]*\)/\1/' ReleaseTitle.md
  when:
    event:
    - tag
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - "*.vsix"
    title: ReleaseTitle.md
    note: ReleaseNotes.md
  when:
    event:
    - tag
- name: publish extension
  image: node
  environment:
    ACCESS_TOKEN:
      from_secret: azure_token
  commands:
  - npx vsce publish --pat $ACCESS_TOKEN
  when:
    event:
    - tag

trigger:
  ref:
  - refs/heads/master
  - refs/heads/dev
  - refs/pull/**
  - refs/tags/*
  event:
  - push
  - pull_request
  - tag