name: MarkdownConverter
kind: pipeline
type: docker

steps:
- name: install
  image: node
  commands:
  - npm install
- name: build
  image: node
  commands:
  - npm run build
- name: test
  image: node
  commands:
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get install -y libnss3-dev libgtk-3-dev libx11-dev libxss-dev libasound-dev xvfb
  - xvfb-run npm run test

trigger:
  branch:
  - master
  - dev